### ISSUE TITLE
fix Warsh

### ISSUE THREAD

**Issue by elhadjx** [QuranHub/quran-pages-images#1]
this warsh data is the same provided by (https://qurancomplex.gov.sa/)[https://qurancomplex.gov.sa/]
but it's not the real warsh, it's so diffrent. you can look it up.

**Comment by Abdallah-Abdelazim** [comment]
Thank you 🙏
I'm aware of this issue. This data matches the Quran images used in the [Ayat project](https://quran.ksu.edu.sa/ayat/?pg=patches&l=en) which is the one used here in the QuranHub app. 
I couldn't find Warsh metadata other than it that's official and guaranteed for correctness. 
If you know some source please do share with me.
